language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

env:
  - GUZZLE_VERSION=~6.2
  - GUZZLE_VERSION=^7.0

install:
  - composer require guzzlehttp/guzzle:"$GUZZLE_VERSION"
  - composer install

script:
  - composer lint
  - composer test
